package de.tuhh.ict.pshdl.model.extensions;

import de.tuhh.ict.pshdl.model.utils.*;

public enum ProblemDescription implements MetaAccess<ProblemDescription> {
	DESCRIPTION,
	// Did not evaluate
	SUBEXPRESSION_DID_NOT_EVALUATE, SUBEXPRESSION_WIDTH_DID_NOT_EVALUATE, SUBEXPRESSION_DID_NOT_EVALUATE_IN_THIS_CONTEXT, VARIABLE_NOT_RESOLVED,
	// Unsupported type
	ARRAY_ACCESS_NOT_SUPPORTED_FOR_CONSTANTS, BIT_ACCESS_NOT_SUPPORTED_FOR_CONSTANTS, ENUMS_NOT_SUPPORTED_FOR_CONSTANTS, TYPE_NOT_SUPPORTED_FOR_CONSTANTS,
	// Ranges
	BOOLEAN_NOT_SUPPORTED_FOR_RANGES, BIT_NOT_SUPPORTED_FOR_RANGES, ZERO_DIVIDE, POSSIBLY_ZERO_DIVIDE,
	// Others
	NON_PRIMITVE_TYPE_NOT_EVALUATED, CAN_NOT_USE_PARAMETER;

	@Override
	public boolean inherit() {
		return true;
	}
}